version: 2.1

orbs:
  node: circleci/node@latest

jobs:
  test:
    node/lts-browsers:
      steps:
        - checkout
        - node/install-packages
        - run: npm test
        - run: npm run codecov

workflows:
  test:
    jobs:
      - test
