version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - browser-tools/install-chrome
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run codecov

workflows:
  test:
    jobs:
      - test
