version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run codecov

workflows:
  version: 2
  test:
    jobs:
      - test
