version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run codecov

workflows:
  test:
    jobs:
      - test
